name: Build Docker images
on:
  push:
    branches:
      - 'main'
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-latest:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.event_name != 'schedule' }}
          tags: maxkratz/offlineimap:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
