name: Build Docker images only
on:
  push:
    # Run pipeline for commits on branches that are not main
    branches:
      - '!main'
      - 'testing/**'
      - 'feature/**'
      - 'hotfix/**'

jobs:
  build-only:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: maxkratz/offlineimap:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
