name: Build Docker image dev
on:
  push:
    # Run pipeline for commits on branch main
    branches:
      - 'main'
      - '!testing/**'
      - '!feature/**'
      - '!hotfix/**'

jobs:
  build-dev:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push dev
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: maxkratz/offlineimap:dev
          platforms: linux/amd64,linux/arm64,linux/arm/v7
